version: '3'
services:

  mongodb:
    image: mongo
    logging:
      driver: none

  api:
    build: .
    command: npm run server
    environment:
      - NODE_ENV=development
      - P4_AUTH_GOOGLE_KEY
      - P4_AUTH_GOOGLE_SECRET
      - P4_AUTH_GOOGLE_CALLBACK
      - P4_DB_HOST=mongodb
      - P4_TMDB_TOKEN
    volumes:
      - .:/srv/app
    ports:
      - "8000:8000"

  serve:
    build: .
    command: npm run build:watch
    environment:
      - NODE_ENV=development
    volumes:
      - .:/srv/app
    ports:
      - "4200:4200"
