version: '3'
services:

  mongodb:
    image: mongo

  api:
    build: .
    command: bas -c "npm run build && npm run server"
    environment:
      - NODE_ENV=production
      - P4_AUTH_GOOGLE_KEY
      - P4_AUTH_GOOGLE_SECRET
      - P4_AUTH_GOOGLE_CALLBACK
      - P4_DB_HOST=mongodb
    volumes:
      - .:/srv/app
    ports:
      - "8084:8000"
