version: '3'
services:

  postgres:
    image: postgres:10.1
    logging:
      driver: none
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: it2810-g22-p4-dev
    tty: true
    stdin_open: true

  api:
    build: .
    command: npm run server:watch
    environment:
      - NODE_ENV=development
      - P4_AUTH_GOOGLE_KEY
      - P4_AUTH_GOOGLE_SECRET
      - P4_AUTH_GOOGLE_CALLBACK
      - P4_DB_HOST=mongodb
      - P4_PGDB_HOST=postgres
      - P4_TMDB_TOKEN
    volumes:
      - .:/srv/app
    ports:
      - "8000:8000"

  serve:
    build: .
    command: npm run build:watch
    environment:
      - NODE_ENV=development
    volumes:
      - .:/srv/app
